### ISSUE TITLE
Multisite Main Domain Redirect

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/wordpress-onelogin#1]
! [image of SAML] (https://developers.google.com/google-apps/sso/saml_workflow_vertical.gif)

Optimum behaviour would allow users to click on a login link from a subdomain // be redirected to the Identity Provider // Authenticate // then Generate a Response that would redirect back to the subdomain. 
Within ADFS, it doesn't look as if the Relaying Party Trust Identifier can be a wildcard, so ADFS will be looking for the request to come from commons.hwdsb.on.ca/wp-login.php, and it will want to send the response back to commons.hwdsb.on.ca. 

The question seems to be, how do you store the subdomain information in the request to ADFS in a way that it will come back intact, and allow us to redirect to the subdomain upon successful authentication. It must be possible, because attempting to navigate to a specific course in our LMS (D2L) takes me to the Identity Provider, and then takes me back to the subdirectory course (this might be an important distinction: subdomain vs subdirectory) 

This article has helped to clarify some details for me: http://www.mutuallyhuman.com/blog/2013/05/09/choosing-an-sso-strategy-saml-vs-oauth2/

**Comment by r-a-y** [comment]
SAML has a redirect parameter:
https://en.wikipedia.org/wiki/SAML_2.0#HTTP_Redirect_Binding

It looks like the OneLogin plugin accepts a URL for redirect via the 'relaystate' parameter:
https://github.com/pitbulk/wordpress-onelogin/blob/be41498911c4c52fc90f35b23f4ee297af872dd3/onelogin-saml-sso/php/functions.php#L260

We'll need to be able to test the plugin somewhere so I can see what we'd need to do for subdomain redirects.

**Comment by mrjarbenne** [comment]
I think the problem is going to be that the ID Provider can't accept a wildcard for the service provider domain. 

What about a rule that redirects all logins to the main site as a stopgap measure, so I can get SSO up and running. Then we sort out the the subdomain SSO on a test server. 

Would you do that with a plugin, or a rule in htaccess?

**Comment by r-a-y** [comment]
> I think the problem is going to be that the ID Provider can't accept a wildcard for the service provider domain. 

I don't think the ID provider needs a wildcard.  We just need to pass our redirect URL to the main ID provider URL once the plugin is properly set up to handle multisite.  I think at the moment the plugin is still using per-site options instead of network options to save their data.

**Comment by mrjarbenne** [comment]
Thst seems accurate. I've seen instances where admins are configuring the ADFS to connect to individual sites: unscalable with our 5000 blogs.

**Comment by r-a-y** [comment]
> What about a rule that redirects all logins to the main site as a stopgap measure, so I can get SSO up and running. Then we sort out the the subdomain SSO on a test server.

Would you do that with a plugin, or a rule in htaccess?

This could also work as a temporary workaround.  Would probably code this as a plugin so we can set up the subdomain redirect properly.

**Comment by r-a-y** [comment]
> What about a rule that redirects all logins to the main site as a stopgap measure, so I can get SSO up and running. Then we sort out the the subdomain SSO on a test server.

This is the plugin version:
https://gist.githubusercontent.com/r-a-y/e098c67f49a57f5d579c/raw/f4d2cf30608ac804b90e37ead5d313ae7543ebbc/wp-ms-login.php

Throw this in bp-custom.php.  Let me know if subdomain redirects work.

**Comment by mrjarbenne** [comment]
Subdomain redirects work. I needed to turn off a redirect we had on the main domain that took users to their profile. 

Could the plugin redirect to their BP profile if they are coming from the main site, but redirect back to the subdomain if that's where they came from. 

Domain mapped sites do not work with the above bp-custom snippet. On WordPress.com, somehow wp-login and wp-admin always redirect back to the unmapped sub-domain to avoid the certificate errors that ensue from a mapped domain secured through *.commons.hwdsb.on.ca

**Comment by r-a-y** [comment]
> Domain mapped sites do not work with the above bp-custom snippet. On WordPress.com, somehow wp-login.php and wp-admin always redirects back to the unmapped sub-domain to avoid the certificate errors that ensue from a mapped domain secured through *.commons.hwdsb.on.ca. Could that be taken into account?

My snippet should use the subdomain as the redirect and not the mapped site URL.  I'm guessing Mercator overrides calls to `get_site_url()` to use the mapped site.  Need to do more research.

**Comment by r-a-y** [comment]
Try the updated snippet and let me know if the redirect uses the unmapped sub-domain:
https://gist.githubusercontent.com/r-a-y/e098c67f49a57f5d579c/raw/30efa4ec22bd79fec9c295e1883636ab3bf0c63d/wp-ms-login.php

About redirecting to the BP profile, are there any instances where this shouldn't happen on the main site?

**Comment by mrjarbenne** [comment]
Sorry. Just getting back to this now. 

When users are on the main domain, and attempt to log in from the that site, they should be redirected to their BP profile. 

If they are on a subdomain, they should be redirected back to the the subdomain they initiated the login from.

This is the code that we have been using for profile redirect from Brajesh Singh. It doesn't redirect the admin, but that's not an important functionality to recreate here. 

```php
/*Add a filter to filter the redirect url for login*/
add_filter("login_redirect","bpdev_redirect_to_profile",100,3);

function bpdev_redirect_to_profile($redirect_to_calculated,$redirect_url_specified,$user){
/*if no redirect was specified,let us think ,user wants to be in wp-dashboard*/
if(empty($redirect_to_calculated))
	$redirect_to_calculated=admin_url();
	
	/*if the user is not site admin,redirect to his/her profile*/
	if(!is_super_admin($user->ID))
		return bp_core_get_user_domain($user->ID );
	else
		return $redirect_to_calculated; /*if site admin or not logged in,do not do anything much*/
}
```
I tried the snippet before I saw your edit. Not sure if you are aware but it also doesn't seem to allow a user to log out from a domain-mapped site.

**Comment by r-a-y** [comment]
I've updated the login redirect snippet:
https://gist.githubusercontent.com/r-a-y/e098c67f49a57f5d579c/raw/4b9ab2d6fd8769a45af0389b45b330a678a75723/wp-ms-login.php

I've tested it locally and on production and it is working for logins and logouts.  The only thing that needs to be addressed on production is the initial wp-login.php link.  For example, if I go to mrjarbenne.ca and click on the "Login" link, the link uses `https://mrjarbenne.ca` instead of the main Commons link.  When clicked, this causes the certificate error to show up due to the cert only covering the Commons subdomains only.

This can be fixed if we change the login URL to use the main site's login URL all the time.  Do you want me to do this?

I also haven't added the BP profile redirect yet as I want to get this main part working first.

**Comment by mrjarbenne** [comment]
By changing the login url to use the main site every time, will we still be able to hold onto the redirect back to the subsite?

Will this cover the meta widget, and the Membership Request widget login logic as well, if clicked from a domain mapped site?

**Comment by r-a-y** [comment]
I did some tests and the Request Membership plugin would require the user to login twice to work properly.  It still works, but is a bit more cumbersome.

On the other hand, the WP Access Password plugin is going to be problematic unless I recode parts of the logic to work so the sub-site password is checked from the root site prior to redirection.  Currently, the sub-site password is only checked from the sub-site's login page.

**Comment by mrjarbenne** [comment]
Let's not kill ourselves to attend to options like that. It can be the caveat of having your own domain that you can't use certain options. It's a small subsection of users that I can't see needing to password protect their site, and who can use alternate methods to onboard users. 

As long as core login methods work we are good.

**Comment by r-a-y** [comment]
> Let's not kill ourselves to attend to options like that. It can be the caveat of having your own domain that you can't use certain options. It's a small subsection of users that I can't see needing to password protect their site, and who can use alternate methods to onboard users. 

It's not just mapped domains.  I mean sites that have WP Access Password activated will not work, even with subdomains if we force logins from the main site.

----

As discussed [here](https://github.com/hwdsbcommons/wordpress-onelogin/issues/1#issuecomment-91116318), I've also just added the snippet to override the login URL when on a mapped domain to production.  This fixes issues with the SSL cert.

**Comment by mrjarbenne** [comment]
Does something like this fix it? No need to code our own if someone else has solved the problem. 

https://wordpress.org/plugins/password-protected/

**Comment by r-a-y** [comment]
Just tested "Password Protected" and it works with our login redirect code.

The reason why it works is it does not use the wp-login.php page like in WP Access Password.

**Comment by mrjarbenne** [comment]
Is there an easy way to search the database to find all of sites using the password protection so I can manually migrate over (if it's not a ton)

**Comment by r-a-y** [comment]
You could use the WPMU Plugin Stats plugin to find out where the plugin is active:
https://wordpress.org/plugins/wpmu-plugin-stats/

**Comment by mrjarbenne** [comment]
I could, but since converting to the new server, this: https://wordpress.org/support/topic/blank-page-110?replies=8

**Comment by r-a-y** [comment]
I also added another alternative in my last comment.

It also does take a lot of resources, but maybe give it a try when the server isn't busy.

**Comment by mrjarbenne** [comment]
I'll check it. That issue was actually in the theme stats version of the plugin, but I'll give the plugin stats a try. I seem to recall similar issues.

**Comment by mrjarbenne** [comment]
First one white-screened on activation, but the second one seems to be working.

**Comment by mrjarbenne** [comment]
It's network activated. I'll need to sort out who has opted for the option within their privacy settings. Basically who has opted for -4 in the privacy database table.

**Comment by r-a-y** [comment]
> It's network activated.

Darn... what I could do in the meantime is log whoever lands on a site with the WP Access Password set and active and we can just convert sites over to the Password Protected plugin on a case-by-case basis.

The alternative is crafting a nifty MySQL statement that will search across all the DB tables to find sites with WP Access Password active.  MySQL-fu isn't great, but I can try.

**Comment by mrjarbenne** [comment]
I have no "fu" so I'm open to either one.

**Comment by r-a-y** [comment]
For now, I've created a log file.  I'll check the log every once in awhile and let you know the results.

**Comment by mrjarbenne** [comment]
Cool. I'll do the switch as we find them.

**Comment by mrjarbenne** [comment]
Password Protected posts (under Visibility in the Post editor) are now redirecting to the root domain wp-login.php page due to the redirect code in bp-custom created for this ticket (snippet: https://gist.githubusercontent.com/r-a-y/e098c67f49a57f5d579c/raw/4b9ab2d6fd8769a45af0389b45b330a678a75723/wp-ms-login.php)

You can see it at http://sandbox.commons.hwdsb.on.ca. Generic post password is: password

**Comment by r-a-y** [comment]
The issue is you have the "Password Protect" plugin enabled plus the "More Privacy Options" privacy option -- "Visible only to registered users of this site" -- enabled under "Settings > Reading > Site Visibility" for the sub-site.

If you are using the "Password Protect" plugin, you should make the "Settings > Reading > Site Visibility" option either:
* Allow search engines to index this site
* Discourage search engines from indexing this site

**Comment by mrjarbenne** [comment]
Sorry. That was me trying to stage the issue I am seeing on other blogs without properly setting everything up. Try now. It's set to Discourage Search Engines, but still redirects to the main domain wp-login page.

**Comment by r-a-y** [comment]
Should be fixed now.

I'm bailing out of post password submissions so when a user has to enter a password for a post, we're not redirecting back to the root domain's login page for this.  But, this shouldn't matter.

**Comment by mrjarbenne** [comment]
Confirmed it's sorted. Thanks for that.
